### ISSUE TITLE
A few questions: using libs, serve and environment?

### ISSUE THREAD

**Issue by m-abs** [NathanWalker/template-nativescript-nx#3]
Hi @NathanWalker,

Once again you're doing a really cool project, thanks for that :+1: 

I have a few questions:
1. Using libs e.g. `@myprojectname/*` in {N}-ng? 
I ended up creating `libs/package.json` with the name `@myproject/libs` and include my module as `@myproject/libs/mymodule`. I tried configuring `apps/mobile-app-name/tsconfig.json` like it is in the parent project, but I couldn't get it to work at runtime.
2. Might be a silly question, but "ng serve" could this be made to work with the {N}-project? It would be nice to have a common way to run the various apps, e.g. web and native.
3. With ordinary angular apps, the ng-cli creates an environment config, could we do something similar with {N}-ng?

**Comment by NathanWalker** [comment]
Hi @m-abs! Sorry for delay.
Instead of creating `libs/package.json`, just create the package in each subfolder in there.
Did you watch this?
https://egghead.io/lessons/angular-share-a-lib-in-an-nx-workspace-with-a-web-and-nativescript-app

`npm run start.web` or `npm run start.ios` or `npm run start.android` is what I do to create the dev workflow consistency. As usual I always approach with web first mentality so I usually setup default to kick off web so `npm start` will queue up `npm run start.web` but you could set that up anyway you'd like.

However I am aware that the core team has been hard at work trying to get incremental webpack builds working for livesync development mode which would create potentially tighter integrations with webpack which `ng serve` uses and potentially {N} could use that perhaps in future.

The `environment` config folder could be placed in the root of the workspace and imported across libs and apps if you'd like.

**Comment by bytesfromali** [comment]
Hey @NathanWalker I have been following your seed for very long and you have been doing some great work there 👍 . This made me explore Nrwl, I heard about Nrwl and Nx few months back but I hesitated to check it out then. But after your suggestion on the seed wiki I got very much interested to change my mind and check it out.

I kind of figured out how it works overall but I really would love to see your videos on this topic, but they are part of PRO membership on egghead and spending 200$ for 2 videos is too much :) to check out something new as I don't have a pro plan of egghead. Have you uploaded your videos also at some other platform which doesn't need a paid membership.

**Comment by NathanWalker** [comment]
Hi @alimohammad thank you and I completely understand that. 
I am working a course for [NativeScripting](https://nativescripting.com/) which will cover a broader scope of Nx with {N} and the entire course will be less than a yearly subscription for sure. I'm planning to have it out in February.

**Comment by m-abs** [comment]
Hi @NathanWalker 

Thank you for your reply. 
Unfortunately I haven't watched your videos yet. For much the same reason @alimohammad gave, but I'll see it I can get my employer to buy an egghead-membership for me.

@alimohammad egghead also have a monthly subscription, but it's still 40$ for a pro membership.

About the `environment`-config, we need to configure the app for other customers. Things like which backend to use, changes to language, icons, styling etc.

But I've been thinking, it might be better to make most of the app inside /libs and have a tns-app per customer in `/apps/tns-{appname}`.
